/**
 * Model Schema
 */
const Records = require('./models/records')


export const route = {
	method: 'post',
	path: '/zones/:zone_identifier/dns_records',
	type: 'json',
};

export default async(req, res) => {
	if (!req.body.hasOwnProperty('content') || !req.body.hasOwnProperty('name') || !req.body.hasOwnProperty('type')) {
		return {
			error: '404'
		};
	} else {
		let data = req.body || {}
		data.zone_id = req.params.zone_identifier;

		// WIP - This will be replaced by the record_id generated by cloudflare
		let rec_num = Math.floor(Math.random() * 10000)
		data.id = rec_num

		let record = new Records(data)

		record.save()

		return res.send(200, 'OK')
	}


};