/**
 * Model Schema
 */
const Records = require('./models/records')

export const route = {
	method: 'post',
	path: '/zones/:zone_identifier/dns_records',
	type: 'json',
};

export default async(req, res) => {
	if (!req.body.hasOwnProperty('content') || !req.body.hasOwnProperty('name') || !req.body.hasOwnProperty('type')) {
		res.status(403).json({
			result: 'error',
			message: 'Cannot create record - missing required parameters',
			info: {
				type: req.body.type,
				name: req.body.name,
				content: req.body.content
			}
		});
	} else {
		let data = req.body || {}
		data.zone_id = req.params.zone_identifier;
		// WIP - This will be replaced by the record_id generated by cloudflare
		data.id = Math.floor(Math.random() * 10000)

		let record = new Records(data)
		record.save()

		res.status(200).json({
			result: 'success',
			message: 'Record Created',
			info: {
				id: data.id
			},
		});
	}


};