/**
 * Model Schema
 */
const Records = require('../../models/records');

export const route = {
	method: 'post',
	path: '/zones/:zone_identifier/dns_records',
	type: 'json',
};

export default async(req, res) => {
	log.debug({req: req}, 'received request');
	if (!req.body.hasOwnProperty('content')
	|| !req.body.hasOwnProperty('name')
	|| !req.body.hasOwnProperty('type')) {
		log.error('missing parameters');
		res.status(403).json({
			result: 'error',
			message: 'Cannot create record - missing required parameters',
			info: {
				type: req.body.type || '{MISSING}',
				name: req.body.name || '{MISSING}',
				content: req.body.content || '{MISSING}',
			},
		});
	} else {
		let data = req.body || {};
		data.zone_id = req.params.zone_identifier;
		// WIP - This will be replaced by the record_id generated by cloudflare
		data.id = Math.floor(Math.random() * 10000);

		let record = new Records(data);
		record.save();

		log.info('record %s created for zone %s', data.id, req.params.zone_identifier);
		res.status(200).json({
			result: 'success',
			message: 'Record Created',
			info: {
				id: data.id,
			},
		});
	}
};
